/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class izpack_frontend_view_win32_NativeIconAccessor */

#ifndef _Included_izpack_frontend_view_win32_NativeIconAccessor
#define _Included_izpack_frontend_view_win32_NativeIconAccessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     izpack_frontend_view_win32_NativeIconAccessor
 * Method:    initializeIconSet
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT void JNICALL Java_izpack_frontend_view_win32_NativeIconAccessor_initializeIconSet
  (JNIEnv *, jobject, jstring);

/*
 * Class:     izpack_frontend_view_win32_NativeIconAccessor
 * Method:    getNativeBuffers
 * Signature: ()Lizpack/frontend/view/win32/NativeIcon;
 */
JNIEXPORT jobject JNICALL Java_izpack_frontend_view_win32_NativeIconAccessor_getNativeBuffers
  (JNIEnv *, jobject);

/*
 * Class:     izpack_frontend_view_win32_NativeIconAccessor
 * Method:    getNumIcons
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_izpack_frontend_view_win32_NativeIconAccessor_getNumIcons
  (JNIEnv *, jobject);

/*
 * Class:     izpack_frontend_view_win32_NativeIconAccessor
 * Method:    destroyIconSet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_izpack_frontend_view_win32_NativeIconAccessor_destroyIconSet
  (JNIEnv *, jobject);

/*
 * Class:     izpack_frontend_view_win32_NativeIconAccessor
 * Method:    getNativeIcon
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_izpack_frontend_view_win32_NativeIconAccessor_getNativeIcon
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
