// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.izforge.izpack.protobuf;

public final class IzPackProtos {
  private IzPackProtos() {}
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor = buildDescriptor();
  private static
      com.google.protobuf.Descriptors.FileDescriptor
      buildDescriptor() {
    java.lang.String descriptorData =
      "\n\014izpack.proto\022\033com.izforge.izpack.proto" +
      "buf\"\260\003\n\004Info\022\017\n\007appName\030\001 \001(\t\022\022\n\nappVers" +
      "ion\030\002 \001(\t\022\033\n\023installationSubPath\030\003 \001(\t\0224" +
      "\n\007authors\030\004 \003(\0132#.com.izforge.izpack.pro" +
      "tobuf.Author\022\016\n\006appURL\030\005 \001(\t\022\023\n\013javaVers" +
      "ion\030\006 \001(\t\022\023\n\013jdkRequired\030\007 \001(\010\022\025\n\rinstal" +
      "lerBase\030\010 \001(\t\022\021\n\twebDirURL\030\t \001(\t\022\027\n\017unin" +
      "stallerName\030\n \001(\t\022\034\n\024uninstallerConditio" +
      "n\030\013 \001(\t\022\032\n\022summaryLogFilePath\030\014 \001(\t\022\034\n\024p" +
      "ackDecoderClassName\030\r \001(\t\022\031\n\021unpackerCla" +
      "ssName\030\016 \001(\t\022$\n\034writeInstallationInforma" +
      "tion\030\017 \001(\010\022\032\n\022pack200Compression\030\020 \001(\010\"%" +
      "\n\006Author\022\014\n\004name\030\001 \001(\t\022\r\n\005email\030\002 \001(\tB+\n" +
      "\033com.izforge.izpack.protobufB\014IzPackProt" +
      "os";
    try {
      return com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
          new com.google.protobuf.Descriptors.FileDescriptor[] {
          });
    } catch (Exception e) {
      throw new RuntimeException(
        "Failed to parse protocol buffer descriptor for " +
        "\"izpack.proto\".", e);
    }
  }
  
  public static final class Info extends
      com.google.protobuf.GeneratedMessage {
    // Use Info.newBuilder() to construct.
    private Info() {}
    
    private static final Info defaultInstance = new Info();
    public static Info getDefaultInstance() {
      return defaultInstance;
    }
    
    public Info getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.izforge.izpack.protobuf.IzPackProtos.internal_static_com_izforge_izpack_protobuf_Info_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.izforge.izpack.protobuf.IzPackProtos.internal_static_com_izforge_izpack_protobuf_Info_fieldAccessorTable;
    }
    
    // optional string appName = 1;
    private boolean hasAppName;
    private java.lang.String appName_ = "";
    public boolean hasAppName() { return hasAppName; }
    public java.lang.String getAppName() { return appName_; }
    
    // optional string appVersion = 2;
    private boolean hasAppVersion;
    private java.lang.String appVersion_ = "";
    public boolean hasAppVersion() { return hasAppVersion; }
    public java.lang.String getAppVersion() { return appVersion_; }
    
    // optional string installationSubPath = 3;
    private boolean hasInstallationSubPath;
    private java.lang.String installationSubPath_ = "";
    public boolean hasInstallationSubPath() { return hasInstallationSubPath; }
    public java.lang.String getInstallationSubPath() { return installationSubPath_; }
    
    // repeated .com.izforge.izpack.protobuf.Author authors = 4;
    private java.util.List<com.izforge.izpack.protobuf.IzPackProtos.Author> authors_ =
      java.util.Collections.emptyList();
    public java.util.List<com.izforge.izpack.protobuf.IzPackProtos.Author> getAuthorsList() {
      return authors_;
    }
    public int getAuthorsCount() { return authors_.size(); }
    public com.izforge.izpack.protobuf.IzPackProtos.Author getAuthors(int index) {
      return authors_.get(index);
    }
    
    // optional string appURL = 5;
    private boolean hasAppURL;
    private java.lang.String appURL_ = "";
    public boolean hasAppURL() { return hasAppURL; }
    public java.lang.String getAppURL() { return appURL_; }
    
    // optional string javaVersion = 6;
    private boolean hasJavaVersion;
    private java.lang.String javaVersion_ = "";
    public boolean hasJavaVersion() { return hasJavaVersion; }
    public java.lang.String getJavaVersion() { return javaVersion_; }
    
    // optional bool jdkRequired = 7;
    private boolean hasJdkRequired;
    private boolean jdkRequired_ = false;
    public boolean hasJdkRequired() { return hasJdkRequired; }
    public boolean getJdkRequired() { return jdkRequired_; }
    
    // optional string installerBase = 8;
    private boolean hasInstallerBase;
    private java.lang.String installerBase_ = "";
    public boolean hasInstallerBase() { return hasInstallerBase; }
    public java.lang.String getInstallerBase() { return installerBase_; }
    
    // optional string webDirURL = 9;
    private boolean hasWebDirURL;
    private java.lang.String webDirURL_ = "";
    public boolean hasWebDirURL() { return hasWebDirURL; }
    public java.lang.String getWebDirURL() { return webDirURL_; }
    
    // optional string uninstallerName = 10;
    private boolean hasUninstallerName;
    private java.lang.String uninstallerName_ = "";
    public boolean hasUninstallerName() { return hasUninstallerName; }
    public java.lang.String getUninstallerName() { return uninstallerName_; }
    
    // optional string uninstallerCondition = 11;
    private boolean hasUninstallerCondition;
    private java.lang.String uninstallerCondition_ = "";
    public boolean hasUninstallerCondition() { return hasUninstallerCondition; }
    public java.lang.String getUninstallerCondition() { return uninstallerCondition_; }
    
    // optional string summaryLogFilePath = 12;
    private boolean hasSummaryLogFilePath;
    private java.lang.String summaryLogFilePath_ = "";
    public boolean hasSummaryLogFilePath() { return hasSummaryLogFilePath; }
    public java.lang.String getSummaryLogFilePath() { return summaryLogFilePath_; }
    
    // optional string packDecoderClassName = 13;
    private boolean hasPackDecoderClassName;
    private java.lang.String packDecoderClassName_ = "";
    public boolean hasPackDecoderClassName() { return hasPackDecoderClassName; }
    public java.lang.String getPackDecoderClassName() { return packDecoderClassName_; }
    
    // optional string unpackerClassName = 14;
    private boolean hasUnpackerClassName;
    private java.lang.String unpackerClassName_ = "";
    public boolean hasUnpackerClassName() { return hasUnpackerClassName; }
    public java.lang.String getUnpackerClassName() { return unpackerClassName_; }
    
    // optional bool writeInstallationInformation = 15;
    private boolean hasWriteInstallationInformation;
    private boolean writeInstallationInformation_ = false;
    public boolean hasWriteInstallationInformation() { return hasWriteInstallationInformation; }
    public boolean getWriteInstallationInformation() { return writeInstallationInformation_; }
    
    // optional bool pack200Compression = 16;
    private boolean hasPack200Compression;
    private boolean pack200Compression_ = false;
    public boolean hasPack200Compression() { return hasPack200Compression; }
    public boolean getPack200Compression() { return pack200Compression_; }
    
    public static com.izforge.izpack.protobuf.IzPackProtos.Info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.izforge.izpack.protobuf.IzPackProtos.Info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.izforge.izpack.protobuf.IzPackProtos.Info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.izforge.izpack.protobuf.IzPackProtos.Info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.izforge.izpack.protobuf.IzPackProtos.Info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.izforge.izpack.protobuf.IzPackProtos.Info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.izforge.izpack.protobuf.IzPackProtos.Info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.izforge.izpack.protobuf.IzPackProtos.Info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.izforge.izpack.protobuf.IzPackProtos.Info prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.izforge.izpack.protobuf.IzPackProtos.Info.newBuilder()
      private Builder() {}
      
      com.izforge.izpack.protobuf.IzPackProtos.Info result = new com.izforge.izpack.protobuf.IzPackProtos.Info();
      
      protected com.izforge.izpack.protobuf.IzPackProtos.Info internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.izforge.izpack.protobuf.IzPackProtos.Info();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.izforge.izpack.protobuf.IzPackProtos.Info.getDescriptor();
      }
      
      public com.izforge.izpack.protobuf.IzPackProtos.Info getDefaultInstanceForType() {
        return com.izforge.izpack.protobuf.IzPackProtos.Info.getDefaultInstance();
      }
      
      public com.izforge.izpack.protobuf.IzPackProtos.Info build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.izforge.izpack.protobuf.IzPackProtos.Info buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.izforge.izpack.protobuf.IzPackProtos.Info buildPartial() {
        if (result.authors_ != java.util.Collections.EMPTY_LIST) {
          result.authors_ =
            java.util.Collections.unmodifiableList(result.authors_);
        }
        com.izforge.izpack.protobuf.IzPackProtos.Info returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional string appName = 1;
      public boolean hasAppName() {
        return result.hasAppName();
      }
      public java.lang.String getAppName() {
        return result.getAppName();
      }
      public Builder setAppName(java.lang.String value) {
        result.hasAppName = true;
        result.appName_ = value;
        return this;
      }
      public Builder clearAppName() {
        result.hasAppName = false;
        result.appName_ = "";
        return this;
      }
      
      // optional string appVersion = 2;
      public boolean hasAppVersion() {
        return result.hasAppVersion();
      }
      public java.lang.String getAppVersion() {
        return result.getAppVersion();
      }
      public Builder setAppVersion(java.lang.String value) {
        result.hasAppVersion = true;
        result.appVersion_ = value;
        return this;
      }
      public Builder clearAppVersion() {
        result.hasAppVersion = false;
        result.appVersion_ = "";
        return this;
      }
      
      // optional string installationSubPath = 3;
      public boolean hasInstallationSubPath() {
        return result.hasInstallationSubPath();
      }
      public java.lang.String getInstallationSubPath() {
        return result.getInstallationSubPath();
      }
      public Builder setInstallationSubPath(java.lang.String value) {
        result.hasInstallationSubPath = true;
        result.installationSubPath_ = value;
        return this;
      }
      public Builder clearInstallationSubPath() {
        result.hasInstallationSubPath = false;
        result.installationSubPath_ = "";
        return this;
      }
      
      // repeated .com.izforge.izpack.protobuf.Author authors = 4;
      public java.util.List<com.izforge.izpack.protobuf.IzPackProtos.Author> getAuthorsList() {
        return java.util.Collections.unmodifiableList(result.authors_);
      }
      public int getAuthorsCount() {
        return result.getAuthorsCount();
      }
      public com.izforge.izpack.protobuf.IzPackProtos.Author getAuthors(int index) {
        return result.getAuthors(index);
      }
      public Builder setAuthors(int index, com.izforge.izpack.protobuf.IzPackProtos.Author value) {
        result.authors_.set(index, value);
        return this;
      }
      public Builder setAuthors(int index, com.izforge.izpack.protobuf.IzPackProtos.Author.Builder builderForValue) {
        result.authors_.set(index, builderForValue.build());
        return this;
      }
      public Builder addAuthors(com.izforge.izpack.protobuf.IzPackProtos.Author value) {
        if (result.authors_.isEmpty()) {
          result.authors_ = new java.util.ArrayList<com.izforge.izpack.protobuf.IzPackProtos.Author>();
        }
        result.authors_.add(value);
        return this;
      }
      public Builder addAuthors(com.izforge.izpack.protobuf.IzPackProtos.Author.Builder builderForValue) {
        if (result.authors_.isEmpty()) {
          result.authors_ = new java.util.ArrayList<com.izforge.izpack.protobuf.IzPackProtos.Author>();
        }
        result.authors_.add(builderForValue.build());
        return this;
      }
      public Builder addAllAuthors(
          java.lang.Iterable<? extends com.izforge.izpack.protobuf.IzPackProtos.Author> values) {
        if (result.authors_.isEmpty()) {
          result.authors_ = new java.util.ArrayList<com.izforge.izpack.protobuf.IzPackProtos.Author>();
        }
        super.addAll(values, result.authors_);
        return this;
      }
      public Builder clearAuthors() {
        result.authors_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional string appURL = 5;
      public boolean hasAppURL() {
        return result.hasAppURL();
      }
      public java.lang.String getAppURL() {
        return result.getAppURL();
      }
      public Builder setAppURL(java.lang.String value) {
        result.hasAppURL = true;
        result.appURL_ = value;
        return this;
      }
      public Builder clearAppURL() {
        result.hasAppURL = false;
        result.appURL_ = "";
        return this;
      }
      
      // optional string javaVersion = 6;
      public boolean hasJavaVersion() {
        return result.hasJavaVersion();
      }
      public java.lang.String getJavaVersion() {
        return result.getJavaVersion();
      }
      public Builder setJavaVersion(java.lang.String value) {
        result.hasJavaVersion = true;
        result.javaVersion_ = value;
        return this;
      }
      public Builder clearJavaVersion() {
        result.hasJavaVersion = false;
        result.javaVersion_ = "";
        return this;
      }
      
      // optional bool jdkRequired = 7;
      public boolean hasJdkRequired() {
        return result.hasJdkRequired();
      }
      public boolean getJdkRequired() {
        return result.getJdkRequired();
      }
      public Builder setJdkRequired(boolean value) {
        result.hasJdkRequired = true;
        result.jdkRequired_ = value;
        return this;
      }
      public Builder clearJdkRequired() {
        result.hasJdkRequired = false;
        result.jdkRequired_ = false;
        return this;
      }
      
      // optional string installerBase = 8;
      public boolean hasInstallerBase() {
        return result.hasInstallerBase();
      }
      public java.lang.String getInstallerBase() {
        return result.getInstallerBase();
      }
      public Builder setInstallerBase(java.lang.String value) {
        result.hasInstallerBase = true;
        result.installerBase_ = value;
        return this;
      }
      public Builder clearInstallerBase() {
        result.hasInstallerBase = false;
        result.installerBase_ = "";
        return this;
      }
      
      // optional string webDirURL = 9;
      public boolean hasWebDirURL() {
        return result.hasWebDirURL();
      }
      public java.lang.String getWebDirURL() {
        return result.getWebDirURL();
      }
      public Builder setWebDirURL(java.lang.String value) {
        result.hasWebDirURL = true;
        result.webDirURL_ = value;
        return this;
      }
      public Builder clearWebDirURL() {
        result.hasWebDirURL = false;
        result.webDirURL_ = "";
        return this;
      }
      
      // optional string uninstallerName = 10;
      public boolean hasUninstallerName() {
        return result.hasUninstallerName();
      }
      public java.lang.String getUninstallerName() {
        return result.getUninstallerName();
      }
      public Builder setUninstallerName(java.lang.String value) {
        result.hasUninstallerName = true;
        result.uninstallerName_ = value;
        return this;
      }
      public Builder clearUninstallerName() {
        result.hasUninstallerName = false;
        result.uninstallerName_ = "";
        return this;
      }
      
      // optional string uninstallerCondition = 11;
      public boolean hasUninstallerCondition() {
        return result.hasUninstallerCondition();
      }
      public java.lang.String getUninstallerCondition() {
        return result.getUninstallerCondition();
      }
      public Builder setUninstallerCondition(java.lang.String value) {
        result.hasUninstallerCondition = true;
        result.uninstallerCondition_ = value;
        return this;
      }
      public Builder clearUninstallerCondition() {
        result.hasUninstallerCondition = false;
        result.uninstallerCondition_ = "";
        return this;
      }
      
      // optional string summaryLogFilePath = 12;
      public boolean hasSummaryLogFilePath() {
        return result.hasSummaryLogFilePath();
      }
      public java.lang.String getSummaryLogFilePath() {
        return result.getSummaryLogFilePath();
      }
      public Builder setSummaryLogFilePath(java.lang.String value) {
        result.hasSummaryLogFilePath = true;
        result.summaryLogFilePath_ = value;
        return this;
      }
      public Builder clearSummaryLogFilePath() {
        result.hasSummaryLogFilePath = false;
        result.summaryLogFilePath_ = "";
        return this;
      }
      
      // optional string packDecoderClassName = 13;
      public boolean hasPackDecoderClassName() {
        return result.hasPackDecoderClassName();
      }
      public java.lang.String getPackDecoderClassName() {
        return result.getPackDecoderClassName();
      }
      public Builder setPackDecoderClassName(java.lang.String value) {
        result.hasPackDecoderClassName = true;
        result.packDecoderClassName_ = value;
        return this;
      }
      public Builder clearPackDecoderClassName() {
        result.hasPackDecoderClassName = false;
        result.packDecoderClassName_ = "";
        return this;
      }
      
      // optional string unpackerClassName = 14;
      public boolean hasUnpackerClassName() {
        return result.hasUnpackerClassName();
      }
      public java.lang.String getUnpackerClassName() {
        return result.getUnpackerClassName();
      }
      public Builder setUnpackerClassName(java.lang.String value) {
        result.hasUnpackerClassName = true;
        result.unpackerClassName_ = value;
        return this;
      }
      public Builder clearUnpackerClassName() {
        result.hasUnpackerClassName = false;
        result.unpackerClassName_ = "";
        return this;
      }
      
      // optional bool writeInstallationInformation = 15;
      public boolean hasWriteInstallationInformation() {
        return result.hasWriteInstallationInformation();
      }
      public boolean getWriteInstallationInformation() {
        return result.getWriteInstallationInformation();
      }
      public Builder setWriteInstallationInformation(boolean value) {
        result.hasWriteInstallationInformation = true;
        result.writeInstallationInformation_ = value;
        return this;
      }
      public Builder clearWriteInstallationInformation() {
        result.hasWriteInstallationInformation = false;
        result.writeInstallationInformation_ = false;
        return this;
      }
      
      // optional bool pack200Compression = 16;
      public boolean hasPack200Compression() {
        return result.hasPack200Compression();
      }
      public boolean getPack200Compression() {
        return result.getPack200Compression();
      }
      public Builder setPack200Compression(boolean value) {
        result.hasPack200Compression = true;
        result.pack200Compression_ = value;
        return this;
      }
      public Builder clearPack200Compression() {
        result.hasPack200Compression = false;
        result.pack200Compression_ = false;
        return this;
      }
    }
  }
  
  public static final class Author extends
      com.google.protobuf.GeneratedMessage {
    // Use Author.newBuilder() to construct.
    private Author() {}
    
    private static final Author defaultInstance = new Author();
    public static Author getDefaultInstance() {
      return defaultInstance;
    }
    
    public Author getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.izforge.izpack.protobuf.IzPackProtos.internal_static_com_izforge_izpack_protobuf_Author_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.izforge.izpack.protobuf.IzPackProtos.internal_static_com_izforge_izpack_protobuf_Author_fieldAccessorTable;
    }
    
    // optional string name = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional string email = 2;
    private boolean hasEmail;
    private java.lang.String email_ = "";
    public boolean hasEmail() { return hasEmail; }
    public java.lang.String getEmail() { return email_; }
    
    public static com.izforge.izpack.protobuf.IzPackProtos.Author parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.izforge.izpack.protobuf.IzPackProtos.Author parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.izforge.izpack.protobuf.IzPackProtos.Author parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.izforge.izpack.protobuf.IzPackProtos.Author parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.izforge.izpack.protobuf.IzPackProtos.Author parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.izforge.izpack.protobuf.IzPackProtos.Author parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.izforge.izpack.protobuf.IzPackProtos.Author parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.izforge.izpack.protobuf.IzPackProtos.Author parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.izforge.izpack.protobuf.IzPackProtos.Author prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.izforge.izpack.protobuf.IzPackProtos.Author.newBuilder()
      private Builder() {}
      
      com.izforge.izpack.protobuf.IzPackProtos.Author result = new com.izforge.izpack.protobuf.IzPackProtos.Author();
      
      protected com.izforge.izpack.protobuf.IzPackProtos.Author internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.izforge.izpack.protobuf.IzPackProtos.Author();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.izforge.izpack.protobuf.IzPackProtos.Author.getDescriptor();
      }
      
      public com.izforge.izpack.protobuf.IzPackProtos.Author getDefaultInstanceForType() {
        return com.izforge.izpack.protobuf.IzPackProtos.Author.getDefaultInstance();
      }
      
      public com.izforge.izpack.protobuf.IzPackProtos.Author build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.izforge.izpack.protobuf.IzPackProtos.Author buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.izforge.izpack.protobuf.IzPackProtos.Author buildPartial() {
        com.izforge.izpack.protobuf.IzPackProtos.Author returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = "";
        return this;
      }
      
      // optional string email = 2;
      public boolean hasEmail() {
        return result.hasEmail();
      }
      public java.lang.String getEmail() {
        return result.getEmail();
      }
      public Builder setEmail(java.lang.String value) {
        result.hasEmail = true;
        result.email_ = value;
        return this;
      }
      public Builder clearEmail() {
        result.hasEmail = false;
        result.email_ = "";
        return this;
      }
    }
  }
  
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_izforge_izpack_protobuf_Info_descriptor =
      getDescriptor().getMessageTypes().get(0);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_izforge_izpack_protobuf_Info_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_com_izforge_izpack_protobuf_Info_descriptor,
          new java.lang.String[] { "AppName", "AppVersion", "InstallationSubPath", "Authors", "AppURL", "JavaVersion", "JdkRequired", "InstallerBase", "WebDirURL", "UninstallerName", "UninstallerCondition", "SummaryLogFilePath", "PackDecoderClassName", "UnpackerClassName", "WriteInstallationInformation", "Pack200Compression", },
          com.izforge.izpack.protobuf.IzPackProtos.Info.class,
          com.izforge.izpack.protobuf.IzPackProtos.Info.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_izforge_izpack_protobuf_Author_descriptor =
      getDescriptor().getMessageTypes().get(1);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_izforge_izpack_protobuf_Author_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_com_izforge_izpack_protobuf_Author_descriptor,
          new java.lang.String[] { "Name", "Email", },
          com.izforge.izpack.protobuf.IzPackProtos.Author.class,
          com.izforge.izpack.protobuf.IzPackProtos.Author.Builder.class);
}
